# Generated by Django 4.0.3 on 2022-04-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto5_website', '0002_alternativa_pergunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='turma',
        ),
        migrations.AddField(
            model_name='aluno',
            name='empregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='conteudo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='perfil',
            field=models.IntegerField(choices=[(1, 'dominancia'), (2, 'influencia'), (3, 'cautela'), (4, 'estabilidade')]),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teste',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
