# Generated by Django 4.0.3 on 2022-04-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto5_website', '0003_remove_aluno_turma_aluno_empregado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='empregado',
            field=models.BooleanField(default=False),
        ),
    ]
