# Generated by Django 4.0.3 on 2022-04-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto5_website', '0005_remove_resultado_empregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='perfil',
            field=models.CharField(default='', max_length=50),
        ),
    ]
