# Generated by Django 4.0.3 on 2022-05-17 00:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projeto5_website', '0007_rename_perfil_resultado_perfildominante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expire_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ra',
            field=models.CharField(max_length=14),
        ),
    ]
